
services:
  redis:
    image: 'redis:7'
    ports:
      - '6379:6379'
    volumes:
      - ./redis-data:/data
    environment:
      REDIS_ARGS: '--appendonly yes'
  frontend1:
    restart: on-failure
    build: ./frontend
    hostname: frontend1
    ports:
      - '81:3000'
  frontend2:
    restart: on-failure
    build: ./frontend
    hostname: frontend2
    ports:
      - '82:3000'
  backend1:
    restart: on-failure
    build: ./backend
    hostname: backend1
    ports:
      - '83:3000'
    environment:
      REDIS_URL: 'redis://192.168.235.46:6379'
  backend2:
    restart: on-failure
    build: ./backend
    hostname: backend2
    ports:
      - '84:3000'
    environment:
      REDIS_URL: 'redis://192.168.235.46:6379'
  nginx:
    build: ./nginx
    ports:
    - '80:80'
    - '8080:8080'
    depends_on:
    - frontend1
    - frontend2
    - backend1
    - backend2


