
services:
  redis:
    image: 'redis/redis-stack:6.2.6-v17'
    ports:
      - '6379:6379'
      - '8001:8001'
    volumes:
      - ./redis-data:/data
    environment:
      REDIS_ARGS: '--appendonly yes'
  backend1:
    restart: on-failure
    build: backend
    hostname: backend1
    ports:
      - '83:8080'
    environment:
      REDIS_URL: 'redis://redis:6379'
    depends_on:
      - redis
  backend2:
    restart: on-failure
    build: backend
    hostname: backend2
    ports:
      - '84:8080'
    environment:
      REDIS_URL: 'redis://redis:6379'
    depends_on:
      - redis
  nginx:
    build:
      context: ./
      dockerfile: nginx/dev-Dockerfile
    ports:
    - '80:80'
    depends_on:
    - backend1
    - backend2


